@extends('layout')
@section('content')

    <script> document.title = "Collectors Place | Üzenetek"</script>
    <div class="row messageBox">
        <div class="col-3 personsChatOnleft" id="personsChatOnleft">
            <h3 id="chatString">Chatek</h3>
            @foreach($chats as $chat)
                <div class="personChat" id="personChatDiv{{$chat->user_id}}" onclick="getChat({{$chat->user_id}})">
                    <img src="{{asset('profilepics/'.$chat->user_profilepic)}}" class="profilePicMessages mt-3" style="float: left">
                    <b><p class="align-middle messagesNev">{{$chat->user_username}}</p></b>
                    @for($i = 0; $i < count($lasts); $i++)
                        @foreach($lasts[$i] as $last)
                            @if($last->message_from == $chat->user_id || $last->message_to == $chat->user_id)
                                @foreach(session()->get('user') as $data)
                                    @if($last->message_from == $data->user_id)
                                        <p class="lastTexts" id="lastText{{$last->message_to}}">Te: {{$last->message_text}}</p>
                                    @else
                                        <p class="lastTexts" id="lastText{{$last->message_from}}">{{$last->message_text}}</p>
                                    @endif
                                @endforeach
                            @endif
                        @endforeach
                    @endfor
                </div>
            @endforeach
        </div>
        <div class="col-9" id="messagesChatBox">
            <div class="chatmessages" id="chatmessages"></div>

            <div id="inputtextbox" style="visibility: hidden">
                <form id="ajax" class="form-horizontal">
                    @csrf
                    <input type="hidden" name = "otherUserId" id="otherUserId">
                    <input type="hidden" name = "offerId" id="offerId">
                    <div class="formTextBar">
                        <input type="text" placeholder="Ide írd az üzeneted!" name="messagetext" id="messagetext" value="" required>
                        <button class="btn btn-primary"><label class="fa fa-paper-plane"></label></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

<script>
    let otherId = 0;
    let offerId;
    let lastMessageId = 0;
    const napok = ['Vasárnap','Hétfő','Kedd','Szerda','Csütörtök','Péntek','Szombat'];

    let getChat = (id) => {
        lastMessageId = 0;

        otherId = id;

        let divek = document.getElementById("personsChatOnleft").children;
        for(var i = 0; i < divek.length; i++) {
            divek[i].style.backgroundColor = 'white';
        }

        let div = document.getElementById('personChatDiv'+id);
        div.style.backgroundColor = '#bfbfbf';

        document.getElementById('chatString').style.backgroundColor = 'gray';

        $.ajax({
            url: '/getmessage/'+id,
            type: 'get',
            dataType: 'json',
            async:false,
            success: function (response){
                var len = 0;
                if(response['data'] != 0){
                    len = response['data'].length;
                }

                @foreach(session()->get('user') as $data)
                {{$nowuserid = $data->user_id}}
                @endforeach

                if(len > 0){
                    var message_id = response['data'][len-1].id;
                    if(message_id > lastMessageId){
                        lastMessageId = message_id;

                        /* Chatbox kiürítése */
                        const chatbox = document.getElementById('chatmessages');
                        chatbox.innerHTML = "";

                        for(var i=0;i<len;i++){
                            var message_from = response['data'][i].message_from;
                            var message_to = response['data'][i].message_to;
                            var message_text = response['data'][i].message_text;
                            var message_timehm = response['data'][i].message_time_hm;
                            var message_day = response['data'][i].message_day;
                            if(i > 0){
                                var message_day_before = response['data'][i-1].message_day;
                            }
                            var message_date_ymd = response['data'][i].message_date_ymd;
                            if (message_day_before !== message_day){
                                let string = "<div class='mt-2'><p class='dayOfTheWeek'>"+napok[message_day]+", "+message_date_ymd+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                            var autogenerated = response['data'][i].message_autogenerated;
                            if(autogenerated == 1){
                                var message_offer_id = response['data'][i].message_offer_id;
                                $.ajax({
                                    url: '/getofferformessage/' + message_offer_id,
                                    type: 'get',
                                    dataType: 'json',
                                    async:false,
                                    success: function (response2) {
                                        var len2 = 0;
                                        if (response['data'] != 0) {
                                            len2 = response['data'].length;
                                        }

                                        if(len2 > 0)
                                        {
                                            var theme = response2['data'][0].theme_name;
                                            var offcards = response2['data'][0].offcards;
                                            var receivecards = response2['data'][0].receivecards;

                                            let string = "<div class='idk' style='margin-left: auto; margin-right: auto;margin-top: 2rem;width: 80%'> <div class='row mt-2'> <h2>"+theme+"</h2> </div> <hr> <div class='row rowMeg'> <div class='col'> <h4>Kínál:</h4> <p class='kinal'>"+offcards+"</p> </div> <div class='col'> <h4>Keres:</h4> <p class='keres'>"+receivecards+"</p> </div> </div> </div>";
                                            chatbox.innerHTML += string;
                                        }
                                    }
                                });
                            }
                            if(message_from == {{$nowuserid}}){
                                let string = "<div class='chatbubble p-2 m-0 position-relative'><p>"+message_text+"</p></div>";
                                chatbox.innerHTML += string;
                                string = "<div class='message_footer2'><p class='timeMessage'>"+message_timehm+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                            else{
                                let string = "<div class='chatbubbleReceive p-2 m-0 position-relative'><p>"+message_text+"</p></div>";
                                chatbox.innerHTML += string;
                                string = "<div class='message_footer'><p class='timeMessage'>"+message_timehm+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                        }
                        $('#chatmessages').scrollTop($('#chatmessages')[0].scrollHeight);
                        offerId = response['data'][0].message_offer_id;

                        document.getElementById('offerId').value = offerId;
                        document.getElementById('otherUserId').value = otherId;

                        var lastmessage = response['data'][len-1].message_text;
                        var lastmessagesender = response['data'][len-1].message_from;
                        if(lastmessagesender == {{$nowuserid}}){
                            document.getElementById('lastText'+otherId).innerHTML = "Te: "+lastmessage;
                        }
                        else {
                            document.getElementById('lastText'+otherId).innerHTML = lastmessage;
                        }
                    }
                }
                document.getElementById('inputtextbox').style.visibility = 'visible';

                document.getElementById("ajax").reset();
            }
        })
    }

    setInterval(function(){
        id = otherId;
        $.ajax({
            url: '/getmessage/'+id,
            type: 'get',
            dataType: 'json',
            async:false,
            success: function (response){
                var len = 0;
                if(response['data'] != 0){
                    len = response['data'].length;
                }

                @foreach(session()->get('user') as $data)
                {{$nowuserid = $data->user_id}}
                @endforeach

                if(len > 0){
                    var message_id = response['data'][len-1].id;
                    if(message_id > lastMessageId) {
                        lastMessageId = message_id;

                        /* Chatbox kiürítése */
                        const chatbox = document.getElementById('chatmessages');
                        chatbox.innerHTML = "";

                        for(var i=0;i<len;i++){
                            var message_from = response['data'][i].message_from;
                            var message_to = response['data'][i].message_to;
                            var message_text = response['data'][i].message_text;
                            var message_timehm = response['data'][i].message_time_hm;
                            var message_day = response['data'][i].message_day;
                            if(i > 0){
                                var message_day_before = response['data'][i-1].message_day;
                            }
                            var message_date_ymd = response['data'][i].message_date_ymd;
                            var autogenerated = response['data'][i].message_autogenerated;
                            console.log(autogenerated);
                            if (message_day_before != message_day){
                                let string = "<div class='mt-2'><p class='dayOfTheWeek'>"+napok[message_day]+", "+message_date_ymd+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                            if(autogenerated == 1){
                                var message_offer_id = response['data'][i].message_offer_id;
                                $.ajax({
                                    url: '/getofferformessage/' + message_offer_id,
                                    type: 'get',
                                    dataType: 'json',
                                    async:false,
                                    beforeSend: function() {
                                        $("#loaderDiv").show();
                                    },
                                    success: function (response2) {
                                        var len2 = 0;
                                        if (response['data'] != 0) {
                                            len2 = response['data'].length;
                                        }

                                        @foreach(session()->get('user') as $data)
                                        {{$nowuserid = $data->user_id}}
                                        @endforeach

                                        if(len2 > 0)
                                        {
                                            var theme = response2['data'][0].theme_name;
                                            var offcards = response2['data'][0].offcards;
                                            var receivecards = response2['data'][0].receivecards;

                                            let string = "<div class='idk' style='margin-left: auto; margin-right: auto;margin-top: 2rem'> <div class='row mt-2'> <h2>"+theme+"</h2> </div> <hr> <div class='row rowMeg'> <div class='col'> <h4>Kínál:</h4> <p class='kinal'>"+offcards+"</p> </div> <div class='col'> <h4>Keres:</h4> <p class='keres'>"+receivecards+"</p> </div> </div> </div>";
                                            chatbox.innerHTML += string;
                                        }
                                    }
                                });
                            }
                            if(message_from == {{$nowuserid}}){
                                let string = "<div class='chatbubble p-2 m-0 position-relative'><p>"+message_text+"</p></div>";
                                chatbox.innerHTML += string;
                                string = "<div class='message_footer2'><p class='timeMessage'>"+message_timehm+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                            else{
                                let string = "<div class='chatbubbleReceive p-2 m-0 position-relative'><p>"+message_text+"</p></div>";
                                chatbox.innerHTML += string;
                                string = "<div class='message_footer'><p class='timeMessage'>"+message_timehm+"</p></div>";
                                chatbox.innerHTML += string;
                            }
                        }
                        var lastmessage = response['data'][len-1].message_text;
                        var lastmessagesender = response['data'][len-1].message_from;
                        if(lastmessagesender == {{$nowuserid}}){
                            document.getElementById('lastText'+otherId).innerHTML = "Te: "+lastmessage;
                        }
                        else {
                            document.getElementById('lastText'+otherId).innerHTML = lastmessage;
                        }
                    }
                }
            }
        })
    }, 1000);

    window.onload = function() {
        $(document).ready(function () {
            $("#ajax").on('submit', function(event) {
                event.preventDefault();
                $.ajax({
                    type: "post",
                    url: "{{route('sendmessage')}}",
                    dataType: "json",
                    data: $('#ajax').serialize()
                });

                document.getElementById("ajax").reset();
                getChat(otherId);
                $('#chatmessages').scrollTop($('#chatmessages')[0].scrollHeight);
            });
        });
    }
</script>
